Fix system rspec tests
lsa-mis/room_ready pull request #74
Opened 2024-06-13 22:41 UTC by britaumich

All spec/system tests should run.
Commands:

- SHOW_BROWSER=true rspec spec/system/<file_name>
- rspec spec/system/<file_name>
- rspec spec/system/*

2024-06-14 22:22 UTC, britaumich commented
@Mohammad4844  
I edited rspec tests moving mock_login(user) after allow(LdapLookup)... statements.
Now they work with no network.
That was a great suggestion.
I removed all sleep commands to run tests faster.

2024-06-17 17:10 UTC, Mohammad4844 requested changes
Some of the tests fail **_sometimes_**. They throw a Selenium error, and I'm pretty sure it's because the rspec code runs faster than the server can respond (it only happens when you're dealing with alert popups, like when it asks 'are you sure you want to delete this?'). 

I tried using capybara's built in helpers to deal with alerts (`dismiss_confirm` and `accept_confirm`), and they seem to solve the issue since they have a built in waiting functionality. I added the code as comments to each of the test case to make it work.

2024-06-17 17:11 UTC, Mohammad4844 commented on spec/system/common_attributes_controller_spec.rb
>          page.driver.browser.switch_to.alert.dismiss
```
dismiss_confirm 'Are you sure you want to delete this Common Attribute?' do
  find(:css, 'i.bi.bi-trash-fill.text-danger').click
end
```

2024-06-17 17:11 UTC, Mohammad4844 commented on spec/system/zones_controller_spec.rb
>          page.driver.browser.switch_to.alert.dismiss
```
dismiss_confirm 'Are you sure you want to delete this zone?' do
  find(:css, 'i.bi.bi-trash-fill.text-danger').click
end
```

2024-06-17 17:11 UTC, Mohammad4844 commented on spec/system/zones_controller_spec.rb
>          page.driver.browser.switch_to.alert.accept
```
accept_confirm 'Are you sure you want to delete this zone?' do
  find(:css, 'i.bi.bi-trash-fill.text-danger').click
end
```

2024-06-19 00:17 UTC, britaumich commented
@Mohammad4844 All tests right now run as single files and all together.
Please check it they run for you.
I'll keep dismiss_browser_dialog and accept_browser_dialog just for reference.

2024-06-20 18:38 UTC, palinaskakun approved these changes
code looks good, all tests pass, no errors

2024-06-20 19:01 UTC, charlieezh submitted a review, later dismissed
all tests passed on my end, looking good

2024-06-20 20:44 UTC, Mohammad4844 approved these changes

2024-06-20 21:56 UTC, merged